previewsEnabled: true
databases:
  - name: actioncable-testdb
    databaseName: actest
    user: actest

services:
  - type: web
    name: actioncable-test
    env: ruby
    plan: free
    healthCheckPath: /health
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    autoDeploy: false
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: actioncable-testdb
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
  - type: pserv
    name: redis
    env: docker
    dockerfilePath: ./Dockerfile.redis
    disk:
      name: data
      mountPath: /var/lib/redis
      sizeGB: 10
