version: "3"

volumes:
  postgres_data_free:

services:
  app:
    # See https://aka.ms/vscode-remote/containers/non-root for details.
    user: vscode

    build:
      context: ..
      dockerfile: .devcontainer/base.Dockerfile
      args:
        # Update 'VARIANT' to pick a Ruby version: 2, 2.7, 2.6, 2.5
        VARIANT: 3
        USER_UID: 1000
        USER_GID: 1000
        NODE_VERSION: lts/*

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      DD_APM_ENABLED: false
      RAILS_ENV: development
      REDIS_HOST: redis

    volumes:
      - ..:/workspace:cached
      - $HOME/.ssh/:/home/vscode/.ssh/ # Mount the ssh folder to authenticate with github

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    links:
      - db
      - redis

  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres_data_free:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: "redis:5-alpine"
    command: redis-server
    ports:
      - "6379:6379"
